### ISSUE TITLE
多线程异常

### ISSUE THREAD

**Issue by whuvr** [hengyunabc/redis-id-generator#1]
下载源码测试，开启500个线程测试会出现偶尔Could not return the resource to the pool异常

**Comment by hengyunabc** [comment]
500个线程太多了，可以考虑设置下redis pool的大小。
除非redis pool里真的有500个连接，否则在压力测试下都是有可能出现这个异常的。

另外，可以说下500线程下的测试的qps是多少不？ :)

**Comment by magiccash** [comment]
ID的生成key有点问题吧，这样生成的id，如果数据汇总可以通过id排序吗？为了保证这个，redis的key不应该包含partition,local miliSecondKey = prefix .. tag ..'_' .. partition

**Comment by hengyunabc** [comment]
@magiccash 没有太理解你的意思，ID是唯一的，当然可以排序。

**Comment by magiccash** [comment]
就是1毫秒里面生成了两个id，属于不同分片，自增id一样，排序的时候是谁在前，在后

**Comment by hengyunabc** [comment]
@magiccash 排序的时直接以ID做long型来排序。比如一个用户发帖子，那么这个用户的帖子排序直接以时间排序就可以了，而如果两个帖子ID的时间是一样的，那么顺序出不会有问题。

而partition是在ID的中间部分，所以这个排序的顺序已经决定了，和最后的seq没有关系。

而每一个partition的seq对应一个redis key，这样可以提高单位时间生成的序列的数量。

**Comment by magiccash** [comment]
还是有点不懂，那这样是不关心1毫秒里面数据的顺序了？排序只和时间有关？

**Comment by hengyunabc** [comment]
@magiccash 大部分数据都不需要严格的顺序。以毫秒做时间排序就足够了，比如商品订单，用户发的文章等。

**Comment by magiccash** [comment]
嗯，我个人有点完偏执，发现问题，总想找办法解决。如果我不用partition做redis的key，再将 id中partition和seq位置换下，是不是就能解决好这个问题了？

**Comment by hengyunabc** [comment]
@magiccash 可以看下这个：http://blog.csdn.net/hengyunabc/article/details/19025973

绝大部分分布式ID生成方案都是 时间 + 分片ID + seq，这个是大家都有充分考虑的。

**Comment by magiccash** [comment]
好的，多谢。我就是从这个blog链接到这里的
