### ISSUE TITLE
生成的id重复问题

### ISSUE THREAD

**Issue by EdwardsBean** [hengyunabc/redis-id-generator#2]
你好，我在demo中添加了所有生成的id放到安全的map key中。最后得到的id数量不正确，说明id重复了。

我的环境是单点redis。可能的原因是什么呢？

**Comment by hengyunabc** [comment]
非常感谢。的确是有重复了。

原因比较微妙，最开始设计时，在redis上做计数的key是带有毫秒的，第一版是改redis的代码来增加了一个获取时间的command。

后来，redis内置了time命令之后，改为利用redis的time命令。但是redis的lua脚本里限制了，执行time命令之后不能再执行write操作。所以把做计数的key里去掉了毫秒数。

但是这个实际上是有问题的。简而言之，获取到time这个时间点和计数key失效并不是绝对的一致的，导致后面生成的ID可能会重复。

新改的方案，改回了原始的设计，在计数key里加入了毫秒，这样子则保证了不会在同一个毫秒里出现重复的ID。

因为使用到了`redis.replicate_commands()`，所以要求要用3.2版本以上的redis server。
