### ISSUE TITLE
集群key分布插槽的问题

### ISSUE THREAD

**Issue by lijunyong** [hengyunabc/redis-id-generator#3]
集群中三台master负责的插槽是都是某个范围的，你如何保证三个key分布到三台master上。

**Comment by hengyunabc** [comment]
###集群实现原理
假定集群里有3个节点，则节点1返回的seq是：

```
0, 3, 6, 9, 12 ...
```

节点2返回的seq是

```
1, 4, 7, 10, 13 ...
```

节点3返回的seq是

```
2, 5, 8, 11, 14 ...
```

这样每个节点返回的数据都是唯一的。

---

客户端在调用获取seq时，采用轮循的办法，依次从不同的redis服务器里获取ID。

**Comment by lijunyong** [comment]
你在lua脚本里用来incrby的key，redis集群key的分布是按一致性哈希算法来的
