### ISSUE TITLE
关于jedis调用Lua脚本的问题

### ISSUE THREAD

**Issue by lijunyong** [hengyunabc/redis-id-generator#4]
在lua脚本中有一个key做incrby，通过jedis调用，通过keys *命令，这个key并没有设置到redis中，我通过./bin/redis-cli --eval redis-script-node1.lua是有设置这个key的

**Comment by hengyunabc** [comment]
key是很快过期的，只有5毫秒。你跑下benchmark，然后再用`keys *`就可以看到了。 或者你把脚本里的 5毫秒改大点。

**Comment by lijunyong** [comment]
我昨天重写了你的Lua，在生产环境不需要让这个key过期。

**Comment by hengyunabc** [comment]
不过期的话，大量的key不用光内存？即使是redis配置了LRU也不是很好。
